from gym.envs.registration import register

register(
    id='3d-v0',
    entry_point='gym_foo3d.envs:FooEnv',
)
register(
    id='3d-v1',
    entry_point='gym_foo3d.envs:FooEnv1',
)
register(
    id='3d-v2',
    entry_point='gym_foo3d.envs:FooEnv2',
)
register(
    id='3d-v3',
    entry_point='gym_foo3d.envs:FooEnv3',
)
register(
    id='3d-v4',
    entry_point='gym_foo3d.envs:FooEnv4',
)
register(
    id='3d-v5',
    entry_point='gym_foo3d.envs:FooEnv5',
)
register(
    id='3d-v6',
    entry_point='gym_foo3d.envs:FooEnv6',
)
register(
    id='3d-v7',
    entry_point='gym_foo3d.envs:FooEnv7',
)
